;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #282A2E
background-alt = #373B41
foreground = #ffffff 
primary = #3b8ac4
secondary = #8ABEB7
alert = #A54242
disabled = #707880

[bar/example]
width = 100%
height = 18pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 2

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = CaskaydiaCove Nerd Font:style=Regular;2

modules-left = xworkspaces xwindow
modules-right = battery pulseaudio xkeyboard memory cpu wifi date powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; tray-position = left

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

pin-workspaces = true

label-active = %name%
label-active-font = 1
label-active-background = ${colors.background-alt}
label-active-underline= #fafafa
label-active-padding = 1

label-occupied = %name%
label-occupied-font = 1
label-occupied-padding = 1

label-urgent = %name%
label-urgent-font = 1
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-font = 1
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:45: +%
label-foreground = #FFDA00

[module/battery]
type = internal/battery

full-at = 90

; format-low once this charge percentage is reached
; Default: 10
low-at = 15

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP1

format-discharging-prefix = " "
format-discharging-prefix-foreground = #fce703
label-discharging = %percentage%%

format-charging-prefix = " "
format-charging-prefix-foreground = #3ec195
label-charging = %percentage%%

format-full-prefix = " "
format-full-prefix-foreground = #34ea15
label-full = %percentage%%

format-low-prefix = " "
format-low-prefix-foreground = #ff0028
label-low = %percentage%%
; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 5

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = ""
label-muted-foreground = ${colors.primary}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.foreground}

format =  <label-layout>
format-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = 
label-disconnected-foreground =  #FF0000

[module/wifi]
type = custom/script
exec = ~/.config/polybar/wifi.sh
tail = true

format = <label>
label = %output%
format-foreground = #00FF00

click-left = ~/.config/polybar/wifi-click.sh
click-right = ~/.config/polybar/wifi-click-alt.sh

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.foreground}

format =  <label> 
formant-foreground = ${colors.primary}

[module/powermenu]
type = custom/menu

label-open =
label-close = 
label-close-foreground = #ff0000
label-separator = ¦ 
label-separator-margin = 1

menu-0-0 =  
menu-0-0-foreground= #0099ff
menu-0-0-exec = reboot -i
menu-0-1 =  
menu-0-1-foreground = #000aff
menu-0-1-exec = poweroff -i

[settings]
screenchange-reload = true
pseudo-transparency = true



